ttm classifier
chauhankaranraj/ocp-ci-analysis pull request #7
Opened 2021-07-26 19:28 UTC by oindrillac

## Related Issues and Dependencies

…

## This introduces a breaking change

- [ ] Yes
- [ ] No

## This Pull Request implements

… Explain your changes.

## Description

2021-07-26 21:46 UTC, chauhankaranraj requested changes
Just a comment about metric template stuff, otherwise /lgtm :)

2021-07-26 21:46 UTC, chauhankaranraj commented on notebooks/data-sources/oc-github-repo/ceph_communication.ipynb
> +{
I'm not sure if this notebook is required. Can't we just add the metric template notebook to the path in `github_PR_EDA.ipynb` nb, like this?
```python
metric_template_path = "../TestGrid/metrics"
if metric_template_path not in sys.path:
    sys.path.insert(1, metric_template_path)

from ipynb.fs.defs.metric_template import (    # noqa: E402
    CephCommunication,
    save_to_disk,
)
```

2021-07-26 21:54 UTC, oindrillac commented on notebooks/data-sources/oc-github-repo/ceph_communication.ipynb
> +{
I wasnt sure if that's possible. Perfect, I will add this

2021-07-27 13:48 UTC, oindrillac commented on notebooks/data-sources/oc-github-repo/ceph_communication.ipynb
> +{
@chauhankaranraj made the changes 🙂

2021-07-27 13:51 UTC, chauhankaranraj approved these changes

2021-07-27 13:51 UTC, merged